# Generated by Django 6.0.2 on 2026-04-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_department_team_dependencies_team_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
    ]
