# Generated by Django 6.0.2 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='team',
            name='downstream_dependencies',
            field=models.ManyToManyField(blank=True, related_name='upstream_dependencies', to='teams.team'),
        ),
    ]
