# Generated by Django 6.0.2 on 2026-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
