# Generated by Django 6.0.2 on 2026-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code_repositories',
            field=models.TextField(blank=True, help_text='GitHub/GitLab URLs, one per line'),
        ),
    ]
