# Generated by Django 6.0.2 on 2026-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_code_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_channels',
            field=models.TextField(blank=True, help_text='Slack channels, Teams channels or email addresses, one per line'),
        ),
    ]
