# Generated by Django 6.0.2 on 2026-04-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_meeting_recipient_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
